version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_jira
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_jira
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=${POSTGRES_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./resources:/app/resources
    restart: no
    depends_on:
      - postgres
    networks:
      - app_network

  nginx:
    container_name: nginx_jira
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/config/nginx.conf
    depends_on:
      - app

networks:
  app_network:
    driver: bridge

volumes:
  pgdata:
    driver: local