version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_jira
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_jira
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - /resources:/app/resources
    restart: no
    depends_on:
      - postgres
    networks:
      - app_network

  nginx:
    container_name: nginx_jira
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - /config/nginx.conf:/config
    depends_on:
      - app

networks:
  app_network:
    driver: bridge

volumes:
  pgdata:
    driver: local